/*
 * CakePhpCustumizerPanel.java
 *
 * Created on 2011/09/16, 23:34:44
 */
package org.cakephp.netbeans.ui.customizer;

import javax.swing.JTextField;

/**
 *
 * @author junichi11
 */
public class CakePhpCustomizerPanel extends javax.swing.JPanel {
        private static final long serialVersionUID = -7471518120349007940L;

	/** Creates new form CakePhpCustumizerPanel */
	public CakePhpCustomizerPanel() {
		initComponents();
	}
	
	public JTextField getAppNameField(){
		return appNameField;
	}
	
	public void setAppNameField(String appName){
		appNameField.setText(appName);
	}
	
	public boolean isAutoCreateView(){
		return autoCreateViewCheckBox.isSelected();
	}
	
	public void setAutoCreateView(boolean isAuto){
		autoCreateViewCheckBox.setSelected(isAuto);
	}
        
        public boolean isUseProjectDirectory(){
                return useProjectDirectoryCheckBox.isSelected();
        }
        
        public void setUseProjectDirectory(boolean isCheck){
                useProjectDirectoryCheckBox.setSelected(isCheck);
        }
        
        public String getCakePhpDirTextField(){
                return cakePhpDirTextField.getText();
        }
        
        public void setCakePhpDirTextField(String cakePhpDir){
                cakePhpDirTextField.setText(cakePhpDir);
        }
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appNameLabel = new javax.swing.JLabel();
        appNameField = new javax.swing.JTextField();
        autoCreateViewCheckBox = new javax.swing.JCheckBox();
        useProjectDirectoryCheckBox = new javax.swing.JCheckBox();
        cakePhpDirLabel = new javax.swing.JLabel();
        cakePhpDirTextField = new javax.swing.JTextField();

        appNameLabel.setText(org.openide.util.NbBundle.getMessage(CakePhpCustomizerPanel.class, "CakePhpCustomizerPanel.appNameLabel.text")); // NOI18N

        appNameField.setText(org.openide.util.NbBundle.getMessage(CakePhpCustomizerPanel.class, "CakePhpCustomizerPanel.appNameField.text")); // NOI18N
        appNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appNameFieldActionPerformed(evt);
            }
        });

        autoCreateViewCheckBox.setText(org.openide.util.NbBundle.getMessage(CakePhpCustomizerPanel.class, "CakePhpCustomizerPanel.autoCreateViewCheckBox.text")); // NOI18N

        useProjectDirectoryCheckBox.setText(org.openide.util.NbBundle.getMessage(CakePhpCustomizerPanel.class, "CakePhpCustomizerPanel.useProjectDirectoryCheckBox.text")); // NOI18N

        cakePhpDirLabel.setText(org.openide.util.NbBundle.getMessage(CakePhpCustomizerPanel.class, "CakePhpCustomizerPanel.cakePhpDirLabel.text")); // NOI18N

        cakePhpDirTextField.setText(org.openide.util.NbBundle.getMessage(CakePhpCustomizerPanel.class, "CakePhpCustomizerPanel.cakePhpDirTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(appNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appNameField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cakePhpDirLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cakePhpDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(autoCreateViewCheckBox)
                            .addComponent(useProjectDirectoryCheckBox))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appNameLabel)
                    .addComponent(appNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoCreateViewCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(useProjectDirectoryCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cakePhpDirLabel)
                    .addComponent(cakePhpDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void appNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appNameFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_appNameFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appNameField;
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JCheckBox autoCreateViewCheckBox;
    private javax.swing.JLabel cakePhpDirLabel;
    private javax.swing.JTextField cakePhpDirTextField;
    private javax.swing.JCheckBox useProjectDirectoryCheckBox;
    // End of variables declaration//GEN-END:variables
}
