//@PaletteItemRegistrations({
//    @PaletteItemRegistration(
//            paletteid = BaserCmsPaletteFactory.BASER_PALETTE_FOLDER,
//            category = BaserCmsPaletteFactory.BASERCMS3_CATEGORY,
//            itemid = "title",
//            body = "<?php $this->BcBaser->title() ?>",
//            name = "title",
//            tooltip = "<?php $this->BcBaser->title() ?>",
//            icon16 = CakePhp.BASER_ICON_16,
//            icon32 = CakePhp.BASER_ICON_32),
//    @PaletteItemRegistration(
//            paletteid = BaserCmsPaletteFactory.BASER_PALETTE_FOLDER,
//            category = BaserCmsPaletteFactory.BASERCMS3_CATEGORY,
//            itemid = "icon",
//            body = "<?php $this->BcBaser->icon() ?>",
//            name = "icon",
//            tooltip = "<?php $this->BcBaser->icon() ?>",
//            icon16 = CakePhp.BASER_ICON_16,
//            icon32 = CakePhp.BASER_ICON_32),
//    @PaletteItemRegistration(
//            paletteid = BaserCmsPaletteFactory.BASER_PALETTE_FOLDER,
//            category = BaserCmsPaletteFactory.BASERCMS3_CATEGORY,
//            itemid = "charset",
//            body = "<?php $this->BcBaser->charset() ?>",
//            name = "charset",
//            tooltip = "<?php $this->BcBaser->charset() ?>",
//            icon16 = CakePhp.BASER_ICON_16,
//            icon32 = CakePhp.BASER_ICON_32),
//    @PaletteItemRegistration(
//            paletteid = BaserCmsPaletteFactory.BASER_PALETTE_FOLDER,
//            category = BaserCmsPaletteFactory.BASERCMS3_CATEGORY,
//            itemid = "metaDescription",
//            body = "<?php $this->BcBaser->metaDescription() ?>",
//            name = "metaDescription",
//            tooltip = "<?php $this->BcBaser->metaDescription() ?>",
//            icon16 = CakePhp.BASER_ICON_16,
//            icon32 = CakePhp.BASER_ICON_32),
//    @PaletteItemRegistration(
//            paletteid = BaserCmsPaletteFactory.BASER_PALETTE_FOLDER,
//            category = BaserCmsPaletteFactory.BASERCMS3_CATEGORY,
//            itemid = "metaKeywords",
//            body = "<?php $this->BcBaser->metaKeywords() ?>",
//            name = "metaKeywords",
//            tooltip = "<?php $this->BcBaser->metaKeywords() ?>",
//            icon16 = CakePhp.BASER_ICON_16,
//            icon32 = CakePhp.BASER_ICON_32),
//    @PaletteItemRegistration(
//            paletteid = BaserCmsPaletteFactory.BASER_PALETTE_FOLDER,
//            category = BaserCmsPaletteFactory.BASERCMS3_CATEGORY,
//            itemid = "scripts",
//            body = "<?php $this->BcBaser->scripts() ?>",
//            name = "scripts",
//            tooltip = "<?php $this->BcBaser->scripts() ?>",
//            icon16 = CakePhp.BASER_ICON_16,
//            icon32 = CakePhp.BASER_ICON_32),
//    @PaletteItemRegistration(
//            paletteid = BaserCmsPaletteFactory.BASER_PALETTE_FOLDER,
//            category = BaserCmsPaletteFactory.BASERCMS3_CATEGORY,
//            itemid = "func",
//            body = "<?php $this->BcBaser->func() ?>",
//            name = "func",
//            tooltip = "<?php $this->BcBaser->func() ?>",
//            icon16 = CakePhp.BASER_ICON_16,
//            icon32 = CakePhp.BASER_ICON_32),
//    @PaletteItemRegistration(
//            paletteid = BaserCmsPaletteFactory.BASER_PALETTE_FOLDER,
//            category = BaserCmsPaletteFactory.BASERCMS3_CATEGORY,
//            itemid = "css",
//            body = "<?php $this->BcBaser->css('') ?>",
//            name = "css",
//            tooltip = "<?php $this->BcBaser->css('stylesheet_name') ?>",
//            icon16 = CakePhp.BASER_ICON_16,
//            icon32 = CakePhp.BASER_ICON_32),
//    @PaletteItemRegistration(
//            paletteid = BaserCmsPaletteFactory.BASER_PALETTE_FOLDER,
//            category = BaserCmsPaletteFactory.BASERCMS3_CATEGORY,
//            itemid = "js",
//            body = "<?php $this->BcBaser->js('') ?>",
//            name = "js",
//            tooltip = "<?php $this->BcBaser->js('file_name') ?>",
//            icon16 = CakePhp.BASER_ICON_16,
//            icon32 = CakePhp.BASER_ICON_32),
//    @PaletteItemRegistration(
//            paletteid = BaserCmsPaletteFactory.BASER_PALETTE_FOLDER,
//            category = BaserCmsPaletteFactory.BASERCMS3_CATEGORY,
//            itemid = "link",
//            body = "<?php $this->BcBaser->link('', '') ?>",
//            name = "link",
//            tooltip = "<?php $this->BcBaser->link('text', 'url') ?>",
//            icon16 = CakePhp.BASER_ICON_16,
//            icon32 = CakePhp.BASER_ICON_32),
//    @PaletteItemRegistration(
//            paletteid = BaserCmsPaletteFactory.BASER_PALETTE_FOLDER,
//            category = BaserCmsPaletteFactory.BASERCMS3_CATEGORY,
//            itemid = "img",
//            body = "<?php $this->BcBaser->img('', array('alt' => '', 'id' => '')) ?>",
//            name = "img",
//            tooltip = "<?php $this->BcBaser->img('imageURL', array('alt' => '', 'id' => '') ?>",
//            icon16 = CakePhp.BASER_ICON_16,
//            icon32 = CakePhp.BASER_ICON_32),})
// XXX there is a problem when module is built
package org.cakephp.netbeans.basercms.palette;

//import org.cakephp.netbeans.CakePhp;
//import org.netbeans.spi.palette.PaletteItemRegistration;
//import org.netbeans.spi.palette.PaletteItemRegistrations;
