/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cakephp.netbeans.ui.wizards;

import javax.swing.JTextArea;

/**
 *
 * @author junichi11
 */
public class InstallStatusDisplayPanel extends javax.swing.JPanel {
    private static final long serialVersionUID = -5576075807750875530L;

    /**
     * Creates new form InstallStatusDisplayPanel
     */
    public InstallStatusDisplayPanel() {
        initComponents();
    }

    public JTextArea getDisplayStatusTextArea() {
        return displayStatusTextArea;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        installLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayStatusTextArea = new javax.swing.JTextArea();

        installLabel.setText(org.openide.util.NbBundle.getMessage(InstallStatusDisplayPanel.class, "InstallStatusDisplayPanel.installLabel.text")); // NOI18N

        displayStatusTextArea.setColumns(20);
        displayStatusTextArea.setEditable(false);
        displayStatusTextArea.setRows(5);
        jScrollPane1.setViewportView(displayStatusTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(installLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(installLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea displayStatusTextArea;
    private javax.swing.JLabel installLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
