/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2013 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 *
 * Portions Copyrighted 2013 Sun Microsystems, Inc.
 */
package org.cakephp.netbeans.ui.wizards;

import java.awt.Dialog;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.util.NbBundle;

/**
 *
 * @author junichi11
 */
public class NewProjectConfigurationDetailPanel extends javax.swing.JPanel {

    private static final NewProjectConfigurationDetailPanel INSTANCE = new NewProjectConfigurationDetailPanel();

    public static NewProjectConfigurationDetailPanel getDefault() {
        return INSTANCE;
    }

    /**
     * Creates new form NewProjectConfigurationDetailPanel
     */
    public NewProjectConfigurationDetailPanel() {
        initComponents();
    }

    public DBConfigPanel getDbDefaultPanel() {
        return dBConfigDefaultPanel;
    }

    public DBConfigPanel getDbTestPanel() {
        return dBConfigTestPanel;
    }

    public boolean isDbDefault() {
        return defaultCheckBox.isSelected();
    }

    public boolean isDbTest() {
        return testCheckBox.isSelected();
    }

    @NbBundle.Messages({
        "NewProjectConfiguratinDetailPanel.dialog.title=database settings"
    })
    public DialogDescriptor showDialog() {
        DialogDescriptor descriptor = new DialogDescriptor(
                this,
                Bundle.NewProjectConfiguratinDetailPanel_dialog_title(),
                true,
                new Object[]{DialogDescriptor.OK_OPTION},
                null,
                DialogDescriptor.DEFAULT_ALIGN,
                null,
                null);
        Dialog dialog = DialogDisplayer.getDefault().createDialog(descriptor);
        dialog.pack();
        dialog.setVisible(true);
        return descriptor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dBConfigDefaultPanel = new org.cakephp.netbeans.ui.wizards.DBConfigPanel();
        dBConfigTestPanel = new org.cakephp.netbeans.ui.wizards.DBConfigPanel();
        defaultCheckBox = new javax.swing.JCheckBox();
        testCheckBox = new javax.swing.JCheckBox();

        defaultCheckBox.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(defaultCheckBox, org.openide.util.NbBundle.getMessage(NewProjectConfigurationDetailPanel.class, "NewProjectConfigurationDetailPanel.defaultCheckBox.text")); // NOI18N

        testCheckBox.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(testCheckBox, org.openide.util.NbBundle.getMessage(NewProjectConfigurationDetailPanel.class, "NewProjectConfigurationDetailPanel.testCheckBox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dBConfigDefaultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dBConfigTestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defaultCheckBox)
                    .addComponent(testCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dBConfigDefaultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dBConfigTestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.cakephp.netbeans.ui.wizards.DBConfigPanel dBConfigDefaultPanel;
    private org.cakephp.netbeans.ui.wizards.DBConfigPanel dBConfigTestPanel;
    private javax.swing.JCheckBox defaultCheckBox;
    private javax.swing.JCheckBox testCheckBox;
    // End of variables declaration//GEN-END:variables
}
